# Generated by Django 4.2.17 on 2025-01-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aximo', '0003_contactlead_portfoliocategory_portfolio_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
