# Generated by Django 4.2.17 on 2025-01-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aximo', '0004_alter_contactlead_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_in_cents', models.IntegerField()),
                ('features', models.TextField()),
            ],
        ),
    ]
